apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec: # how to behave each any every pod
      containers:
        - name: tickets
          image: lakinduchandula/microservices-ticket-tickets
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY  
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
